services:
  frontend:
    build: .
    command: bun run dev --host
    volumes:
      - ./src:/app/src
    ports:
      - 80:5173
    environment:
      - MODE=development
      - VERCEL_GIT_COMMIT_SHA=unknown
      - PUBLIC_API_URL=http://backend:8000
      - PUBLIC_API_VERSION=v1
      - PUBLIC_POSTHOG_API_KEY=${PUBLIC_POSTHOG_API_KEY}
      - PUBLIC_METICULOUS_RECORDING_TOKEN=${PUBLIC_METICULOUS_RECORDING_TOKEN}
      - PUBLIC_WEGLOT_API_KEY=${PUBLIC_WEGLOT_API_KEY}
      - PUBLIC_GOOGLE_PLACES_API_KEY=${PUBLIC_GOOGLE_PLACES_API_KEY}
      - PUBLIC_CLERK_PUBLISHABLE_KEY=${PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_APP_SECRET=${STREAM_APP_SECRET}
      - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}

    depends_on:
      - backend

  backend:
    build: ./backend
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=local
    depends_on:
      - db

  db:
    build: ./backend/src/core/db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
