name: Rust CI

on:
  push:
    branches: ['master']
    paths: ['src-tauri/**']

  pull_request:
    branches: ['master']
    paths: ['src-tauri/**']

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: webkit2gtk-4.0 libwebkit2gtk-4.0-37 libgtk-3-0 libgtk-3-dev \
            libappindicator3-1 libsoup2.4 javascriptcoregtk-4.0
          version: 1.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Tauri
        run: cargo install tauri-cli
        continue-on-error: true
      - name: Build
        run: cargo tauri build --verbose
      - name: Run tests
        run: cargo test --verbose --manifest-path=src-tauri/Cargo.toml
